### PR TITLE
Suppressing of warning of missing property if it also has an association

### PR DESCRIPTION
**Pull request by srushti**
Since comments exists both directly in post and as an association (and we choose to use the association since it returns all the comments) we get a warning when mogli tries to populate the comments. This warning is a little misleading.
I have done the check based on the existence of a method without the '=' (a getter). It might not be the most elegant but it gets the job done for now.

### CODE REVIEW

**Comment by mmangino** [comment]
Hmm, this seems like an improvement, but not quite right. What do you think about having summary_comments and all_comments. Summary comments would be the hash populating accessor and all_comments would be the association. Does that sound reasonable? That would require some changes to work, but it's probably a better end solution.

**Comment by mmangino** [comment]
One other little thing:

warn_about_invalid_property(method_as_s.chop) if !methods.include?(method_as_s.split('=')[0])

In that line, can you make it something like 

warn_about_invalid_property(method_as_s.chop) unless has_setter_for(method_as_s)

That makes it a little more clear.

**Comment by srushti** [comment]
I liked your suggestion about the sample_comments and all_comments. I've gone ahead and implemented it. There's a new type of property called has_association_with_sample. So far, I've only put it on the comments on post (haven't tested it to see if it applies to any other properties).
I've also removed that line in missing_method altogether. I had only added it because of the warning I was getting when mogli was trying to set comments from the sample.

**Comment by mmangino** [comment]
Awesome. I may tweak this a little bit. I think I would rather allow you to specify a name for the association and the hash populating accessor. I will pull this in shortly.

**Comment by mmangino** [comment]
This is better now. I now set the association on fetch. It likely needs a way to reload, but it seems good enough for now

**Pull request closed without merging**
