### PR TITLE
Mike, please take a look at my pull request.

### PR DESCRIPTION
**Pull request by alexsherstinsky**
Hi, Mike:

I traced the situation when Mogli::Page.find(page_id) fails to find the Facebook Page that in fact exists.  The manifestation of this problem was that hash_or_array in client.rb was 'false', which crashed on "has_key" and "key" in the respective methods.  I added a couple of simple checks to prevent this null pointer exception.

Here are the example of Facebook Pages to demonstrate the inconsistency (the dollar signs are delimiters I use for clarity when printing to stdout):

Case A. Mogli::Page.find does the right thing:
Facebook Page URL=$http://www.facebook.com/crackle$
Mogli::Page.find('/crackle') returns
FB_PAGE=$Crackle$
NUM_LIKES=$35475$

Case B. Mogli::Page.find does not find the Facebook Page:
Facebook Page URL=$http://www.facebook.com/AllClearID$
Mogli::Page.find('/AllClearID') returns
[2011/04/13:17:31:35] FB_PAGE=$$

I also hit the Facebook Open Graph HTTP API to try to see what is going on and found that https://graph.facebook.com/AllClearID returns 'false' on a page, instead of the JSON for that page.

Hence, I believe that this is not the fault of Mogli -- 'hash_or_array.parsed_response" comes up as 'false' for a perfectly valid Facebook Page, because https://graph.facebook.com/AllClearID returns 'false' that page.

At this point, I am wondering who might be able to shed some light on this.  I am going to contact the owners of that page and ask them if they -- somehow -- disabled API access for their company page (which would seem odd, assuming that Facebook even makes it possible).  

Overall, for a vast majority of Facebook Pages, the data is returned as expected.  However, for  a small number of Facebook Pages, I consistently get a null result back.

Thank you for your help and your time.

Sincerely,
--Alex

### CODE REVIEW

**Comment by mmangino** [comment]
You can already create a client for a page using Page#client_for_page, so that commit isn't needed.

Can you come up with a failing tet for this case? I'd love to fix this, but I want to add a test to explain what is happening and I can't currently get the test to fail.

**Comment by mmangino** [comment]
Actually, I was able to make a change in map data that might take care of it. Can you still try to add a failing test and reproduce? Can you open a new pull request with the test and just that fix?

**Comment by alexsherstinsky** [comment]
Hi, Mike:

I think here is what is happening.  I will try to summarize it in quick
bullets:
1) The Page was returning false.  This is consistent with Facebook's
documentation for accessing Facebook Pages that have Country restrictions.
 From an earlier email, "you must be signed in to access a page with Country
restrictions".  This makes sense.  For example, the AllClearID company
serves only U.S. market.
2) The small bug I fixed was that Mogli was checking for nil, but not for
false.  Since Facebook returns false, this came undetected and right into
"has_key", which of course doesn't exist for FalseClass.
3) Here is a simple test case: Try Mogli::Page.find('allclearid') #not case
sensitive, so can try 'AllClearID', etc.  You will get a MethodNotFound
exception.

My understanding is that Mogli::Page#client_for_page operates on an instance
of a Page.  In our case, we are trying to get the data for a Page.  Does
that make sense?  I "fixed" it in my code by simply using
Mogli::Page.find('AllClearID', current_facebook_client) #returns the correct
data when there is a signed in user.

Thank you very much for your time.

Regards,
--Alex
P.S.: If you think this will help, I am happy to write an actual ruby/rails
test case coding up the above example.  The master Mogli code will raise an
exception, while my "fix" will return nil without an exception.  Please let
me know.

**Comment by alexsherstinsky** [comment]
Hi, Mike:

I am happy to do that.  I have a bunch of office things today, so I will get
it done either by tonight or by tomorrow night.

Best,
--Alex

**Comment by alexsherstinsky** [comment]
Hi, Mike:

I just checked, and it looks like you wrote the tests yourself.  Then I used
the latest version of Mogli (0.0.28) in my code, and it works fine, without
throwing exceptions.  So I guess that this closes the present issue.

Thank you so much for your help and responsiveness.

Sincerely,
--Alex

**Comment by mmangino** [comment]
Excellent, that's why I couldn't get the tests to fail.

Mike

On Apr 15, 2011, at 11:46 AM, alexsherstinsky wrote:

> Hi, Mike:
> 
> I just checked, and it looks like you wrote the tests yourself.  Then I used
> the latest version of Mogli (0.0.28) in my code, and it works fine, without
> throwing exceptions.  So I guess that this closes the present issue.
> 
> Thank you so much for your help and responsiveness.
> 
> Sincerely,
> --Alex
> 
> On Thu, Apr 14, 2011 at 7:49 AM, Alex Sherstinsky
> asherstinsky@freejit.comwrote:
> 
> > Hi, Mike:
> > 
> > I am happy to do that.  I have a bunch of office things today, so I will
> > get it done either by tonight or by tomorrow night.
> > 
> > Best,
> > --Alex
> > 
> > On Thu, Apr 14, 2011 at 7:41 AM, mmangino <
> > reply@reply.github.com>wrote:
> > 
> > > Actually, I was able to make a change in map data that might take care of
> > > it. Can you still try to add a failing test and reproduce? Can you open a
> > > new pull request with the test and just that fix?
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/mmangino/mogli/pull/47#issuecomment-1001539
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mmangino/mogli/pull/47#issuecomment-1008276

## 

Mike Mangino
http://www.elevatedrails.com

**Pull request closed without merging**
