### PR TITLE
Added a Place model

### PR DESCRIPTION
**Pull request by spidaman**
I've been playing around with the graph API and noticed there seemed to be no model that handled responses for things that are places, so I added it and it does what I expect. E.g.

bimbos = Mogli::Place.find(56418126832)

### CODE REVIEW

**Comment by mmangino** [comment]
Wow, I don't know how I missed this. Can you rebase this against the most recent code and kill the version bump?

**Comment by pragmaticsc** [comment]
Is there anything I can do to move this along?

**Comment by mmangino** [comment]
Yeah, can somebody rebase it so that it applies again?

**Comment by mmangino** [comment]
This is way too much later, but merged and will be in a release later this week.

**Pull request closed without merging**
