### PR TITLE
Add support to call api methods with custom url and with post method 

### PR DESCRIPTION
**Pull request by cantorrodista**
By default, post method in Mogli::Client uses "https://graph.facebook.com/" as api_path, but sometimes is useful use another "base path" to make calls (for example, to customize an Mogli::Application properties)

### CODE REVIEW

**Comment by mmangino** [comment]
I don't understand, why would you ever do this? how would using a different URL customize a mogli::application?

**Comment by cantorrodista** [comment]
If you want, for example, to set the properties of an Application (Mogli::Aplication) you should call to the "old method":

https://api.facebook.com/method/admin.setAppProperties?properties="what ever here"

And this call is not under the path: https://graph.facebook.com/.

**Comment by mmangino** [comment]
Ah, okay. Got it. What does the response look like? Do you have to include all of the old style parameters? I don't plan on supporting the old REST API. I would file a bug with Facebook and ask them to make that available with their new API.

Mike

On Apr 14, 2011, at 10:51 AM, cantorrodista wrote:

> If you want, for example, to set the properties of an Application (Mogli::Aplication) you should call to the "old method":
> 
> https://api.facebook.com/method/admin.setAppProperties?properties="what ever here"
> 
> And this call is not under the path: https://graph.facebook.com/.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mmangino/mogli/pull/46#issuecomment-1001603

## 

Mike Mangino
http://www.elevatedrails.com

**Comment by ebshimizu** [comment]
It's been over a year, and from what I've gathered, Facebook has still not moved the `dashboard` methods to the new API. Everything I've seen has examples of calling the old REST API to use it in newer applications. For all I know, they might have more methods still to be moved to the new API, but I don't know what they are because I can't find a list of what's missing from the Graph API.

Wrote a method almost identical to this one to access the `dashboard` functions. One nice thing Facebook did is allow access to the REST API with `access_token`, so no old style params have to be passed. Response appears to be a hash. Seems to work just fine.

**Comment by mmangino** [comment]
Honestly, I've supported the old API in the past and I have no desire to do it again. Feel free to create a mogli-additions gem that subclasses Client to allow changing the api path and adds support for any other methods you want.

**Pull request closed without merging**
