### PR TITLE
For issue #126, when the data for a model object is unexpectedly non-json

### PR DESCRIPTION
**Pull request by yitaosun**

### CODE REVIEW

**Comment by yitaosun** [comment]
I don't know how check-ins usually work, but here's my proposed patch for #126.  For the sake of other objects that can unexpectedly receive non-json data, I propose to change hash_populating_accessor to bypass map_data and directly set the instance variable to the string data.

**Comment by yitaosun** [comment]
I wrote write that alternative as well and called it hash_populating_accessor_with_default_field.  The new method will set the string value to the default property (in the case of Address, the street).  In the end, I chose to modify hash_populating_accessor for my personal build.

Something like

``` ruby
    # model.rb
    def self.hash_populating_accessor_with_default_field(method_name,default_field,*klass)
      define_method "#{method_name}=" do |hash|
        hash={default_field:hash} if hash.is_a?(String)
        instance_variable_set("@#{method_name}",client.map_data(hash,klass))
      end
      define_method "#{method_name}" do
        instance_variable_get "@#{method_name}"
      end

      add_creation_method(method_name,klass)

    end

    # place.rb
    module Mogli
      class Place < Model

        ...
        hash_populating_accessor_with_default_field :location, "street", "Address"

```

**Comment by mmangino** [comment]
That's perfect. Can you do a pull request for that so that I give you credit? I'm happy to add the tests.

Mike

**Comment by yitaosun** [comment]
Gladly.  The first check-in had some typos.  I sanity tested the 2nd version (2df29e5).  Let me know if it works.

**Comment by mmangino** [comment]
Thanks! I just added a test, merged this and created a new version.

**Pull request closed without merging**
