### PR TITLE
Check extended permissions for facebook user

### PR DESCRIPTION
**Pull request by bmpercy**
Added a couple of methods to allow checking for extended permissions for a facebook user (e.g. to see if the user has dropped permissions on facebook while logged into your app): has_permission? and check_permissions.

### CODE REVIEW

**Comment by mmangino** [comment]
Can you add a test for this? I want to make sure the right query is sent and that results are handled correctly. Also, this seems a little awkward to use. If you check multiple permissions, you make multiple FQL queries. Would it makes sense to grab all permissions on the first query and then store the results to check each permission?

**Comment by bmpercy** [comment]
Cool, yeah, I guess that was awkward...I was thinking if you wanted to check multiple you'd use the check_permissions, but if you're just interested in one, you'd use has_permission? But I think your suggestion to fetch all and cache them, then just use has_permission? to access the cached perms makes perfect sense.

I'll get on it!

**Comment by bmpercy** [comment]
Hopefully that covers it!

**Comment by mmangino** [comment]
Thanks! Sorry for the delay in pulling this in. My son was born 11/9 and it's been a little hectic around here :)

**Pull request closed without merging**
