### PR TITLE
FQL Multiquery

### PR DESCRIPTION
**Pull request by simianarmy**
Hello Mike, 

I added REST fql.multiquery api support to the Client class.
I left some comments describing my assumptions, & wrote some specs for it.
Works from my real life use tests as well.

### CODE REVIEW

**Comment by mmangino** [comment]
I like most of this, but have a couple of requests.

1) Can you remove the XML option? I don't see any benefit to it.

2) (somewhat optional, but much preferred) Can you make each query return objects of the right type? This may require a wrapper. Something like:

```
f = FqlMultiquery.new
f.add_named_query_for_class("users","select uid from user",Mogli::User)
f.add_named_query_for_class("comment_bodies","select body from comments",Mogli::Comment)
results = f.results
results["users"].first.class.should == Mogli::User
```

Mike

**Comment by simianarmy** [comment]
Will do Mike - give me a sec though been swamped with work the last few

**Comment by simianarmy** [comment]
Hopefully what you had in mind...I kept the fql_multiquery method for direct calling, and added the Mogli::FqlMultiquery class for modular query building and results with proper return objects.

**Comment by mmangino** [comment]
Perfect, thanks!

This is in 0.0.26

Mike

**Pull request closed without merging**
